export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const EMPTY_CART="EMPTY_CART"
export const PRODUCT_LIST="PRODUCT_LIST"
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"
export const SEARCH_PRODUCT="SEARCH_PRODUCT"
export const FETCH_SERVICE="FETCH_SERVICE"
export const SET_FETCH_SERVICE="SET_FETCH_SERVICE"
export const CREATE_FETCH_SERVICE="CREATE_FETCH_SERVICE"
export const SET_CREATE_FETCH_SERVICE="SET_CREATE_FETCH_SERVICE"
export const UPDATE_SERVICE="UPDATE_SERVICE"
export const DELETE_SERVICE="DELETE_SERVICE"




